# Generated by Django 5.0.6 on 2024-06-18 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frms', '0002_product_productpricehistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='branch',
        ),
        migrations.CreateModel(
            name='BranchStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frms.branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frms.product')),
            ],
            options={
                'unique_together': {('branch', 'product')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='branches',
            field=models.ManyToManyField(through='frms.BranchStock', to='frms.branch'),
        ),
    ]
